const QUESTIONS=[
['Attitude','I will absolutely argue just because I can.'],['Attitude','“Because I said so” is not a convincing argument.'],['Attitude','I have a talent for getting the last word.'],['Attitude',"I like pretending I don't know what I'm doing."],['Attitude','I will push a little just to see what happens.'],['Attitude','Being told “no” makes me want to negotiate.'],['Attitude','I can give someone that look without saying a word.'],['Attitude','I know exactly how cute I am when I’m being difficult.'],
['Teasing','I enjoy deliberately being a little annoying.'],['Teasing','I like getting a reaction out of people.'],['Teasing','I will tease someone and then act completely innocent.'],['Teasing','I enjoy making someone work for my cooperation.'],['Teasing','I like playful challenges.'],['Teasing','I sometimes push buttons just because they’re there.'],['Teasing','I can keep a straight face while causing absolute chaos.'],['Teasing','I secretly enjoy being called out for my behavior.'],
['Defiance','I have trouble following rules I think are silly.'],['Defiance','I will question instructions before following them.'],['Defiance','I sometimes do the opposite just to be difficult.'],['Defiance','I like testing boundaries that have already been established.'],['Defiance','I enjoy a little back-and-forth before giving in.'],['Defiance','I have definitely said “make me.”'],['Defiance','I can turn a simple request into a negotiation.'],['Defiance','I like seeing how far I can push my luck.'],
['Chaos','I am usually the one who starts the trouble.'],['Chaos','I can turn innocent situations into mischief.'],['Chaos','I enjoy being a handful.'],['Chaos','I have absolutely no problem admitting I’m being difficult.'],['Chaos','I think “technically, you didn’t say I couldn’t” is a valid argument.'],['Chaos','I enjoy being dramatic for comedic effect.'],['Chaos','I will absolutely exploit a loophole.'],['Chaos','I thrive on chaos.'],
['Caught','I secretly enjoy being caught misbehaving.'],['Caught','Being called out can be surprisingly satisfying.'],['Caught','I like when someone recognizes exactly what I’m doing.'],['Caught','I enjoy having my attitude challenged.'],['Caught','I can go from “I did nothing wrong” to laughing about it very quickly.'],['Caught','I sometimes keep misbehaving because I want attention.'],['Caught','I enjoy the anticipation of finding out what happens next.'],['Caught','Sometimes getting caught is half the fun.'],
['Consequences','I know when I’m pushing my luck.'],['Consequences','I occasionally push it anyway.'],['Consequences','I enjoy playful consequences.'],['Consequences','I like having someone who can actually keep up with me.'],['Consequences','I appreciate someone who doesn’t take my attitude personally.'],['Consequences','I like being challenged when I’m being particularly bratty.'],['Consequences','Deep down, I know when I’ve earned a little correction.'],['Consequences','Sometimes I want someone to finally say, “Okay, that’s enough.”']
];
const TYPE_DATA={
'Princess':{quote:'I shouldn’t have to ask.',traits:['Attitude','Caught']},
'Professional Menace':{quote:'You don’t cause problems. You create opportunities for consequences.',traits:['Defiance','Consequences']},
'Tease':{quote:'But watching you react is half the fun.',traits:['Teasing','Caught']},
'Negotiator':{quote:'Let’s discuss your terms.',traits:['Attitude','Defiance']},
'Instigator':{quote:'Technically, this was your idea.',traits:['Teasing','Chaos']},
'Brat Supreme':{quote:'You knew what you were getting into.',traits:['Chaos','Consequences']}
};
const state={name:'',color:'#ff3f8e',current:0,answers:[],questions:[],scores:{Attitude:0,Teasing:0,Defiance:0,Chaos:0,Caught:0,Consequences:0}};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function rgb(hex){const n=hex.replace('#','');return [parseInt(n.slice(0,2),16),parseInt(n.slice(2,4),16),parseInt(n.slice(4,6),16)].join(',')}
function setColor(color){state.color=color;document.documentElement.style.setProperty('--accent',color);document.documentElement.style.setProperty('--accent-rgb',rgb(color));$$('.color').forEach(b=>b.classList.toggle('active',b.dataset.color===color))}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function show(id){$$('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}
function start(){state.name=$('#nameInput').value.trim()||'Mischief';state.current=0;state.answers=[];state.questions=shuffle(QUESTIONS);Object.keys(state.scores).forEach(k=>state.scores[k]=0);show('#quizScreen');renderQuestion()}
function overall(){return Math.round(state.answers.reduce((a,b)=>a+b,0)/(QUESTIONS.length*5)*100)}
function renderQuestion(){const q=state.questions[state.current], pct=Math.round(state.current/QUESTIONS.length*100);$('#categoryLabel').textContent=q[0];$('#counter').textContent=String(state.current+1).padStart(2,'0')+' / 48';$('#questionNumber').textContent='QUESTION '+(state.current+1);$('#questionText').textContent=q[1];$('#progressBar').style.width=pct+'%';$('#jarPercent').textContent=overall()+'%';$('#miniPercent').textContent=overall()+'%';$$('.ratings button').forEach(b=>{b.disabled=false;b.classList.remove('chosen')})}
function addDecor(el,pct){el.innerHTML='';const symbols=['🍒','♡','✦','🎀','★','🍒','✦','♡'];const count=Math.max(2,Math.ceil(pct/12));for(let i=0;i<count;i++){const s=document.createElement('span');s.className='jar-item';s.textContent=symbols[i%symbols.length];s.style.left=(8+((i*31)%82))+'%';s.style.bottom=(5+((i*17)%Math.max(10,pct)))+'%';s.style.animationDelay=(i*.17)+'s';el.appendChild(s)}}
function updateJar(){const pct=overall();$('#jarFill').style.height=pct+'%';$('#jarPercent').textContent=pct+'%';$('#miniPercent').textContent=pct+'%';addDecor($('#jarItems'),pct);$('#jarCaption').textContent=pct>=90?'Oh. You are a menace.':pct>=70?'The jar is getting dangerously full.':pct>=40?'Okay… there’s definitely a brat in there.':'Your crimes are currently minimal.'}
function answer(score){if(state.answers.length!==state.current)return;state.answers.push(score);state.scores[state.questions[state.current][0]]+=score;const btn=$(`[data-score="${score}"]`);btn.classList.add('chosen');updateJar();if(score===5){$('#jar').classList.remove('shake');void $('#jar').offsetWidth;$('#jar').classList.add('shake')}setTimeout(()=>{state.current++;if(state.current>=QUESTIONS.length)finish();else renderQuestion()},450)}
function type(){const total=overall();if(total>=96)return'Brat Supreme';const s=state.scores;const ranked=Object.entries(s).sort((a,b)=>b[1]-a[1]).map(x=>x[0]);const has=(a,b)=>ranked.indexOf(a)<3&&ranked.indexOf(b)<3;if(has('Teasing','Caught'))return'Tease';if(has('Attitude','Defiance'))return'Negotiator';if(has('Teasing','Chaos'))return'Instigator';if(has('Defiance','Consequences'))return'Professional Menace';return'Princess'}
function finish(){const pct=overall(), t=type(), data=TYPE_DATA[t];$('#resultName').textContent=state.name.toUpperCase();$('#resultPercent').textContent=pct;$('#finalPercent').textContent=pct+'%';$('#resultType').textContent=t;$('#resultQuote').textContent='“'+data.quote+'”';$('#finalFill').style.height=pct+'%';addDecor($('#finalItems'),pct);$('#traits').innerHTML='';Object.entries(state.scores).forEach(([name,val])=>{const row=document.createElement('div');row.className='trait';row.innerHTML=`<span>${name}</span><div class="trait-track"><div class="trait-fill"></div></div><strong>${Math.round(val/40*100)}%</strong>`;row.querySelector('.trait-fill').style.width=Math.round(val/40*100)+'%';$('#traits').appendChild(row)});show('#resultsScreen')}
function save(){const note=$('#saveNote');if(navigator.share){navigator.share({title:'My Brat Jar',text:`${state.name} is ${overall()}% bratty — ${type()}.`}).catch(()=>{});note.textContent='Share sheet opened — send your results wherever you want.'}else{window.print();note.textContent='Print/save as PDF from your browser to keep your result.'}}
$$('.color').forEach(b=>b.addEventListener('click',()=>setColor(b.dataset.color)));$('#startBtn').addEventListener('click',start);$$('.ratings button').forEach(b=>b.addEventListener('click',()=>answer(Number(b.dataset.score))));$('#restartBtn').addEventListener('click',()=>show('#startScreen'));$('#saveBtn').addEventListener('click',save);setColor(state.color);
